<script setup lang="ts">
import { computed, ref } from 'vue'
import ActionDialog from '../../../../components/ActionDialog.vue'
import { onShow, onHide } from '@dcloudio/uni-app'
import { api, isMockMode } from '../../../../services/http'
import { useSessionStore } from '../../../../stores/session'
import { parseAdminLoginCode } from '../../utils/admin-login'
const session=useSessionStore(), busy=ref(false),error=ref(''),notice=ref(''),pending=ref<{id:string;scanSecret:string}|null>(null),context=ref<any>(null),devices=ref<any[]>([])
const allowed=computed(()=>session.roles.some(r=>['ADMIN','SUPER_ADMIN','FINANCE'].includes(r)))
const fmt=(s:string)=>new Date(s).toLocaleString('zh-CN',{hour12:false})
async function load(){if(isMockMode)return;try{await session.hydrate();if(allowed.value)devices.value=await api.get<any[]>('/admin-auth/sessions')}catch(e:any){error.value=e.message||'登录设备读取失败'}}
async function scan(){if(busy.value||isMockMode)return;busy.value=true;error.value='';notice.value='';pending.value=null;context.value=null;try{const result=await uni.scanCode({scanType:['qrCode'],onlyFromCamera:true});const parsed=parseAdminLoginCode(result.result);if(!parsed)throw new Error('这不是金羽电脑后台登录二维码');const info=await api.post(`/admin-auth/requests/${parsed.id}/inspect`,{scanSecret:parsed.scanSecret});pending.value=parsed;context.value=info}catch(e:any){if(!String(e.errMsg||'').includes('cancel'))error.value=e.message||'无法读取二维码，请重新扫描'}finally{busy.value=false}}
async function decide(approve:boolean){if(!pending.value||busy.value)return;busy.value=true;error.value='';try{await api.post(`/admin-auth/requests/${pending.value.id}/${approve?'approve':'reject'}`,{scanSecret:pending.value.scanSecret});notice.value=approve?'已确认，请回到电脑继续操作。':'已拒绝本次登录';pending.value=null;context.value=null;await load()}catch(e:any){error.value=e.message||'请求未完成，请查看电脑状态'}finally{busy.value=false}}
async function revoke(id:string){const confirm=await uni.showModal({title:'撤销电脑登录',content:'这台电脑将立即无法继续访问业务。',confirmText:'撤销登录'});if(!confirm.confirm)return;busy.value=true;error.value='';try{await api.post(`/admin-auth/sessions/${id}/revoke`,{});notice.value='已撤销该电脑登录';await load()}catch(e:any){error.value=e.message||'撤销失败'}finally{busy.value=false}}
async function login(){busy.value=true;try{await session.loginWithWechat();await load()}catch(e:any){error.value=e.message||'微信登录失败'}finally{busy.value=false}}
onShow(load)
onHide(()=>{pending.value=null;context.value=null})
</script>
<template><view class="page pc-login"><view class="card"><text class="heading">电脑后台登录</text><text class="muted intro">在电脑打开管理后台，再用此处扫描登录二维码。</text><view v-if="isMockMode" class="alert">当前为模拟模式，请使用连接正式服务器的小程序。</view><template v-else-if="!session.isAuthenticated"><button :disabled="busy" @tap="login">微信登录</button></template><view v-else-if="!allowed" class="alert">当前账号未获管理员或财务岗位授权，无法登录电脑后台。</view><template v-else><button :disabled="busy" @tap="scan">{{ busy?'正在处理…':'扫描电脑登录二维码' }}</button></template></view><view v-if="error" class="card alert" role="alert">{{ error }}</view><view v-if="notice" class="card notice" role="status">{{ notice }}</view><ActionDialog v-if="context" title="确认是你正在登录" :busy="busy" @close="pending=null;context=null"><view class="confirmation"><text class="muted">核对电脑与手机显示的识别码一致，再确认登录。</text><text class="code">{{ context.confirmationCode }}</text><text class="target">登录网站：{{ context.origin }}</text><text class="muted">有效至 {{ fmt(context.expiresAt) }}</text><text class="muted intro">电脑将获得你当前已授权的管理能力，请只确认自己正在使用的电脑。</text><text v-if="error" class="alert" role="alert">{{ error }}</text></view><template #footer><button :disabled="busy" @tap="decide(true)">确认登录这台电脑</button><button class="secondary" :disabled="busy" @tap="decide(false)">不是我，拒绝登录</button></template></ActionDialog><view v-if="allowed&&!isMockMode" class="card"><view class="section-top"><text class="heading">已登录的电脑</text><button class="secondary refresh" :disabled="busy" @tap="load">刷新</button></view><view v-for="device in devices" :key="device.id" class="device"><text>电脑浏览器</text><text class="muted">登录于 {{ fmt(device.createdAt) }}</text><text class="muted">到期 {{ fmt(device.expiresAt) }}</text><button class="secondary" :disabled="busy" @tap="revoke(device.id)">撤销这台电脑</button></view><text v-if="!devices.length" class="muted">暂无有效电脑会话</text></view></view></template>
<style scoped>.pc-login{padding:28rpx}.card{margin-bottom:24rpx;padding:30rpx}.heading{display:block;font-size:36rpx;font-weight:700;margin-bottom:18rpx}.intro{display:block;margin:20rpx 0;line-height:1.7}.alert{color:#9f2525;background:#fff1f1}.notice{color:#17653d;background:#e7f4eb}.confirmation text{display:block;line-height:1.7}.code{font-size:60rpx;font-weight:800;letter-spacing:8rpx;color:#17653d;margin:24rpx 0;text-align:center}.target{word-break:break-all;font-size:28rpx}.confirmation button{margin-top:20rpx}.section-top{display:flex;justify-content:space-between;align-items:center}.refresh{font-size:26rpx;margin:0;padding:0 20rpx}.device{border-top:1rpx solid #dce5df;padding:24rpx 0}.device text{display:block;margin-bottom:12rpx}.device button{margin-top:16rpx}</style>
