/** A confirmed price change; internal version codes are generated by the server. */
export interface ApplyVenuePriceCommand {
  sourceRuleId?: string;
  sourceRevision?: string;
  name: string;
  timeSlotId?: string;
  weekdayMask: number;
  priceCents: number;
  newcomerPriceCents?: number;
  effectiveFrom: string;
  effectiveTo?: string;
  reason: string;
  idempotencyKey: string;
}

export interface VenuePriceRule {
  id: string;
  code: string;
  version: number;
  name: string;
  timeSlotId: string | null;
  weekdayMask: number;
  priceCents: number;
  newcomerPriceCents: number | null;
  effectiveFrom: string;
  effectiveTo: string | null;
  enabled: boolean;
  updatedAt: string;
  timeSlot?: { id: string; label: string; enabled: boolean } | null;
}

export interface VenuePriceTimeSlot {
  id: string;
  label: string;
  enabled: boolean;
}
